version: "3.6"
services:
  postgres-service:
    image: postgres:11.9
    container_name: postgres-container
    restart: on-failure
    env_file:
      - ./pg.env
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: docker-pgdata
        target: /var/lib/postgres/data

volumes:
  docker-pgdata:
    external: true

networks:
  default:
    external:
      name: pgnetwork
